import {COMMANDS} from "./commands";

/**
 * Maps each command type to an array of suggested next commands.
 * Order matters — first items appear first in the suggestions row.
 */
export const COMMAND_SUGGESTIONS = {
  [COMMANDS.FETCH]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.JSON,
    COMMANDS.IF,
    COMMANDS.LOG,
    COMMANDS.FOR_EACH,
  ],

  [COMMANDS.FIND_NODE]: [
    COMMANDS.GET_INNER_HTML_NODE,
    COMMANDS.INNER_HTML_NODE,
    COMMANDS.GET_ATTRIBUTE_NODE,
    COMMANDS.SET_ATTRIBUTE_NODE,
    COMMANDS.GET_VALUE_OF_INPUT,
    COMMANDS.SET_VALUE_TO_INPUT,
    COMMANDS.NODE_TRIGGER,
    COMMANDS.NODE_EVENT,
    COMMANDS.REMOVE_NODE,
  ],

  [COMMANDS.CREATE_NODE]: [
    COMMANDS.INNER_HTML_NODE,
    COMMANDS.SET_ATTRIBUTE_NODE,
    COMMANDS.APPEND_NODE,
  ],

  [COMMANDS.INIT_VARIABLE]: [
    COMMANDS.IF,
    COMMANDS.LOG,
    COMMANDS.SET,
    COMMANDS.FETCH,
  ],

  [COMMANDS.FOR_EACH]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.IF]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.SET,
    COMMANDS.LOG,
  ],

  [COMMANDS.JSON]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.FOR_EACH,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.GET_FROM_DB]: [
    COMMANDS.IF,
    COMMANDS.INIT_VARIABLE,
    COMMANDS.LOG,
    COMMANDS.JSON,
  ],

  [COMMANDS.WRITE_TO_DB]: [
    COMMANDS.LOG,
    COMMANDS.PUSH_NOTIFICATION,
  ],

  [COMMANDS.GET_INNER_HTML_NODE]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.JSON,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.GET_ATTRIBUTE_NODE]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.GET_VALUE_OF_INPUT]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.OPEN_TAB]: [
    COMMANDS.DELAY,
    COMMANDS.FIND_NODE,
    COMMANDS.REDIRECT,
  ],

  [COMMANDS.DELAY]: [
    COMMANDS.FIND_NODE,
    COMMANDS.FETCH,
    COMMANDS.LOG,
  ],

  [COMMANDS.REDIRECT]: [
    COMMANDS.DELAY,
    COMMANDS.FIND_NODE,
  ],

  [COMMANDS.TEMPLATE]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.INNER_HTML_NODE,
    COMMANDS.LOG,
  ],

  [COMMANDS.FUNC]: [
    COMMANDS.CALL_FUNC,
  ],

  [COMMANDS.CODE]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.CSS]: [
    COMMANDS.FIND_NODE,
    COMMANDS.DELAY,
  ],

  [COMMANDS.APPEND_NODE]: [
    COMMANDS.FIND_NODE,
    COMMANDS.SET_ATTRIBUTE_NODE,
    COMMANDS.NODE_EVENT,
  ],

  [COMMANDS.INNER_HTML_NODE]: [
    COMMANDS.FIND_NODE,
    COMMANDS.LOG,
  ],

  [COMMANDS.SET_ATTRIBUTE_NODE]: [
    COMMANDS.FIND_NODE,
    COMMANDS.LOG,
  ],

  [COMMANDS.MAPPER]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.FOR_EACH,
    COMMANDS.LOG,
  ],

  [COMMANDS.GET_ALL_TABS]: [
    COMMANDS.FOR_EACH,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.FORM_DATA]: [
    COMMANDS.FETCH,
  ],

  [COMMANDS.ARRAY_MAP]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.LOG,
    COMMANDS.FOR_EACH,
  ],

  [COMMANDS.ARRAY_FILTER]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.LOG,
    COMMANDS.FOR_EACH,
  ],

  [COMMANDS.ARRAY_FIND]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.NODE_EVENT]: [
    COMMANDS.INIT_VARIABLE,
    COMMANDS.IF,
    COMMANDS.LOG,
  ],

  [COMMANDS.NODE_TRIGGER]: [
    COMMANDS.DELAY,
    COMMANDS.FIND_NODE,
    COMMANDS.LOG,
  ],

  [COMMANDS.SET_VALUE_TO_INPUT]: [
    COMMANDS.NODE_TRIGGER,
    COMMANDS.FIND_NODE,
    COMMANDS.DELAY,
  ],

  [COMMANDS.GET_KEYS_FROM_DB]: [
    COMMANDS.FOR_EACH,
    COMMANDS.LOG,
  ],

  [COMMANDS.GET_VALUES_FROM_DB]: [
    COMMANDS.FOR_EACH,
    COMMANDS.LOG,
  ],

  [COMMANDS.GET_ENTRIES_FROM_DB]: [
    COMMANDS.FOR_EACH,
    COMMANDS.LOG,
  ],
};