

export const TRIGGERS = {
  LOAD_URL: "URL_LOAD",
  IFRAME_LOAD_URL: "IFRAME_URL_LOAD",
  CALL_SYMLINK: "CALL_SYMLINK",
  LOAD_URL_REG_EXP: "URL_LOAD_REG_EXP",
  ALARM: "ALARM",
  // TAB
  TAB_CREATED: "TAB_CREATED",
  TAB_UPDATED: "TAB_UPDATED",
  TAB_REMOVED: "TAB_REMOVED",
  TAB_MOVED: "TAB_MOVED",
  // Notifications
  NOTIFICATION_CLICKED: "NOTIFICATION_CLICKED",
  NOTIFICATION_CLOSED: "NOTIFICATION_CLOSED",
  // @deprecated
  ACTIVE_PAGE_MANUALLY: "CURRENT_ACTIVE_PAGE"
}

export const LOAD_URL_CONDITION = {
  START: "start",
  CONTAINS: 'contains',
  END: "end"
}
